
FROM python:3.10-slim

WORKDIR /flask_app

# Instalar dependencias Python directamente
RUN pip install Flask==2.3.3 requests==2.31.0 Flask-CORS==4.0.0 gunicorn==21.2.0

# Exponer puerto
EXPOSE 5050

# Comando por defecto
CMD ["python", "flask_app.py"]
