version: "3.4"

services:
  # (Flask)
  demo_web_app:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:5050"
    environment:
      - TZ=UTC
    networks:
      ADSL:
        ipv4_address: 172.30.0.10
    volumes:
      - '/opt/storage/demo_web_app:/flask_app'
    depends_on:
      - demo_api_app
    tty: true
    stdin_open: true

  # (FastAPI)
  demo_api_app:
    restart: "no"
    image: apps/api_dev:1
    ports:
      - "80:80"
    environment:
      - TZ=UTC
    networks:
      ADSL:
        ipv4_address: 172.30.0.20
    volumes:
      - '/opt/storage/demo_api_app:/var/www/html'
    depends_on:
      - demo_api_db

  # (PostgreSQL)
  demo_api_db:
    image: 'bitnami/postgresql:14.9.0'
    ports:
      - '5432:5432'
    environment:
      - TZ=UTC
      - POSTGRESQL_DATABASE=prueba_api_conversiones
      - POSTGRESQL_USERNAME=conversiones_user
      - POSTGRESQL_PASSWORD=muses_c_us_27809
    networks:
      ADSL:
        ipv4_address: 172.30.1.20
    volumes:
      - 'demo_api_db_data:/bitnami/postgresql'

networks:
  ADSL:
    external: true

volumes:
  demo_api_db_data:
    driver: local
